table fecha_salida_capitulo
	dataCategory: Time

	column 'Fecha Salida'
		dataType: dateTime
		isKey
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Fecha Salida

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Mes
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'Nombre del mes'
		dataType: string
		summarizeBy: none
		sourceColumn: Nombre del mes

		annotation SummarizationSetBy = Automatic

	column 'Día de la semana'
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Día de la semana

		annotation SummarizationSetBy = Automatic

	column 'Nombre del día'
		dataType: string
		summarizeBy: none
		sourceColumn: Nombre del día

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Nombre Trimestre'
		dataType: string
		summarizeBy: none
		sourceColumn: Nombre Trimestre

		annotation SummarizationSetBy = Automatic

	partition fecha_salida_capitulo = m
		mode: import
		queryGroup: Fechas
		source =
				let
				    AñoInicio = Date.Year(List.Min(capitulo[Fecha Salida])),
				    AñoFin = Date.Year(List.Max(capitulo[Fecha Salida])),
				    FechaInicio = #date(AñoInicio, 1, 1),
				    FechaFin = #date(AñoFin, 12, 31),
				    ListaFechas = List.Dates(FechaInicio, Number.From(FechaFin)- Number.From(FechaInicio)+1, #duration(1,0,0,0)),
				    #"Convertida en tabla" = Table.FromList(ListaFechas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Convertida en tabla",{{"Column1", "Fecha Salida"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Fecha Salida", type date}}),
				    #"Mes insertado" = Table.AddColumn(#"Tipo cambiado", "Mes", each Date.Month([Fecha Salida]), Int64.Type),
				    #"Año insertado" = Table.AddColumn(#"Mes insertado", "Año", each Date.Year([Fecha Salida]), Int64.Type),
				    #"Nombre del mes insertado" = Table.AddColumn(#"Año insertado", "Nombre del mes", each Date.MonthName([Fecha Salida]), type text),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Nombre del mes insertado",{{"Nombre del mes", Text.Proper, type text}}),
				    #"Día de la semana insertado" = Table.AddColumn(#"Poner En Mayúsculas Cada Palabra", "Día de la semana", each Date.DayOfWeek([Fecha Salida]), Int64.Type),
				    #"Nombre del día insertado" = Table.AddColumn(#"Día de la semana insertado", "Nombre del día", each Date.DayOfWeekName([Fecha Salida]), type text),
				    #"Poner En Mayúsculas Cada Palabra1" = Table.TransformColumns(#"Nombre del día insertado",{{"Nombre del día", Text.Proper, type text}}),
				    #"Trimestre insertado" = Table.AddColumn(#"Poner En Mayúsculas Cada Palabra1", "Trimestre", each Date.QuarterOfYear([Fecha Salida]), Int64.Type),
				    #"Personalizada agregada" = Table.AddColumn(#"Trimestre insertado", "Nombre Trimestre", each Text.From([Trimestre])&"° Trimestre"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Nombre Trimestre", type text}})
				in
				    #"Tipo cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

