table tipo_capitulo

	column 'Código Tipo'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Código Tipo

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Capitulo'
		dataType: string
		summarizeBy: none
		sourceColumn: Tipo de Capitulo

		annotation SummarizationSetBy = Automatic

	partition tipo_capitulo = m
		mode: import
		queryGroup: Dimensiónes
		source =
				let
				    Origen = Csv.Document(File.Contents(url_bd),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"", Int64.Type}, {"Num_episode", Int64.Type}, {"Title", type text}, {"Type", type text}, {"Year_launch", Int64.Type}, {"Rate", Int64.Type}, {"Votes", Int64.Type}, {"Saga", type text}, {"Airdate", type date}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado","Manga Canon","Canon del manga",Replacer.ReplaceText,{"Type"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Mixed Canon/Filler","Mixto (canon y relleno)",Replacer.ReplaceText,{"Type"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Filler","Relleno",Replacer.ReplaceText,{"Type"}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Valor reemplazado2",{"Type"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Filas ordenadas" = Table.Sort(#"Duplicados quitados",{{"Type", Order.Ascending}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Filas ordenadas", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "Type"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Índice", "Código Tipo"}, {"Type", "Tipo de Capitulo"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

