table Devoluciones

	column FechaDevolucion
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: FechaDevolucion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IDTerritorio
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: IDTerritorio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IDProducto
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: IDProducto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CantidadDevuelta
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: CantidadDevuelta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Devoluciones = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaProyecto&"Devoluciones de Productos CicloVida.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"FechaDevolucion", type text}, {"IDTerritorio", Int64.Type}, {"IDProducto", Int64.Type}, {"CantidadDevuelta", Int64.Type}}),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Tipo cambiado", {{"FechaDevolucion", type date}}, "es-419")
				in
				    #"Tipo cambiado con configuración regional"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

