table MEDIDAS

	measure 'Cantidad Ventas' = SUM(Ventas[CantidadOrden])
		formatString: #,0

		changedProperty = IsHidden

	measure 'Cantidad Devoluciones' = SUM(Devoluciones[CantidadDevuelta])
		formatString: #,0

	measure 'Precio Promedio' = ```
			
			    AVERAGE(
			        Productos[Precio]
			    )
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Devoluciones' = COUNT(Devoluciones[CantidadDevuelta])
		formatString: #,0

	measure 'Total Ventas' = DISTINCTCOUNT(Ventas[IDOrden])
		formatString: #,0

	measure 'Tasa de Devoluciones Op/' = [Cantidad Devoluciones]/[Cantidad Ventas]
		formatString: 0.00\ %;-0.00\ %;0.00\ %

	measure 'Tasa de Devoluciones DIVIDE' =
			
			DIVIDE(
			    [Cantidad Devoluciones],
			    [Cantidad Ventas],
			    "Denominador 0"
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %

	measure 'Total Ventas Multiples' = ```
			
			    CALCULATE(
			        [Total Ventas],
			        Ventas[CantidadOrden]>1
			    )
			```
		formatString: #,0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Ventas de Fin de Semana' = ```
			
			    CALCULATE(
			        [Total Ventas],
			        Calendario[Tipo de día]="Fin de Semana"
			    )
			```
		formatString: #,0

	measure 'Total de Devoluciones de Accesorios' = ```
			
			    CALCULATE(
			        [Total Devoluciones],
			        'Categorias de Producto'[CategoriaProducto]="Accesorios"
			    )
			```
		formatString: #,0

	measure 'Total de Ventas de Accesorios' = ```
			
			    CALCULATE(
			        [Cantidad Ventas],
			        'Categorias de Producto'[CategoriaProducto]="Accesorios"
			    )
			```
		formatString: #,0

	measure 'Tasa de Devoluciones de Accesorios' = DIVIDE([Total de Devoluciones de Accesorios],[Total de Ventas de Accesorios])
		formatString: 0.00\ %;-0.00\ %;0.00\ %

	measure 'Todas las Devoluciones' = ```
			
			    CALCULATE(
			        [Total Devoluciones],
			        ALL(Devoluciones)
			    )
			```
		formatString: 0

	measure '% del Total de Devoluciones' = DIVIDE([Total Devoluciones], [Todas las Devoluciones], "No hubo devoluciones")
		formatString: 0.00\ %;-0.00\ %;0.00\ %

	measure 'Precio Promedio Global' = ```
			
			    CALCULATE(
			        [Precio Promedio],
			        ALL(
			            Productos
			        )
			    )
			```
		formatString: #,0.00

	measure 'Ordenes con alto precio' =
			
			CALCULATE(
			    [Total Ventas],
			    FILTER(
			        Productos,
			        Productos[Precio]>[Precio Promedio Global]
			    )
			)
		formatString: #,0

	partition MEDIDAS = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

