table Productos

	column IDProducto
		dataType: int64
		isKey
		formatString: 0
		summarizeBy: none
		sourceColumn: IDProducto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IDSubcategoriaProducto
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: IDSubcategoriaProducto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		summarizeBy: none
		sourceColumn: SKU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		summarizeBy: none
		sourceColumn: Producto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		summarizeBy: none
		sourceColumn: Modelo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Descripcion
		dataType: string
		summarizeBy: none
		sourceColumn: Descripcion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		summarizeBy: none
		sourceColumn: Color

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Talla
		dataType: string
		summarizeBy: none
		sourceColumn: Talla

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estilo
		dataType: string
		summarizeBy: none
		sourceColumn: Estilo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Costo
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Costo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Precio
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Precio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Productos = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaProyecto&"Productos.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDProducto", Int64.Type}, {"IDSubcategoriaProducto", Int64.Type}, {"Costo", type number}, {"Precio", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

