table Territorios

	column IDTerritorio
		dataType: int64
		isKey
		formatString: 0
		summarizeBy: none
		sourceColumn: IDTerritorio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Pais

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Continente
		dataType: string
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: Continente

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía de Territorio'

		level Continente
			column: Continente

		level Pais
			column: Pais

		level Region
			column: Region

	partition Territorios = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaProyecto&"Territorios.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDTerritorio", Int64.Type}, {"Region", type text}, {"Pais", type text}, {"Continente", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

