table DimensionInstitucion

	column 'Codigo Dimension'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Codigo Dimension

		annotation SummarizationSetBy = Automatic

	column 'Dimension Institucion'
		dataType: string
		summarizeBy: none
		sourceColumn: Dimension Institucion

		annotation SummarizationSetBy = Automatic

	partition DimensionInstitucion = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(url_db),[Delimiter=",", Columns=28, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"SIZE"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Índice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "SIZE"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Índice", "Codigo Dimension"}, {"SIZE", "Dimension Institucion"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

