table Enfoque

	column 'Codigo Enfoque'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Codigo Enfoque

		annotation SummarizationSetBy = Automatic

	column Enfoque
		dataType: string
		summarizeBy: none
		sourceColumn: Enfoque

		annotation SummarizationSetBy = Automatic

	partition Enfoque = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(url_db),[Delimiter=",", Columns=28, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"FOCUS"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Índice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "FOCUS"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Índice", "Codigo Enfoque"}, {"FOCUS", "Enfoque"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

