table IntensidadInvestigacion

	column 'Codigo Intensidad'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Codigo Intensidad

		annotation SummarizationSetBy = Automatic

	column 'Intensidad Investigacion'
		dataType: string
		summarizeBy: none
		sourceColumn: Intensidad Investigacion

		annotation SummarizationSetBy = Automatic

	partition IntensidadInvestigacion = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(url_db),[Delimiter=",", Columns=28, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"RES."}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Índice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "RES."}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Índice", "Codigo Intensidad"}, {"RES.", "Intensidad Investigacion"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

