table TipoInstitucion

	column 'Codigo Tipo Institucion'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Codigo Tipo Institucion

		annotation SummarizationSetBy = Automatic

	column 'Tipo Institucion'
		dataType: string
		summarizeBy: none
		sourceColumn: Tipo Institucion

		annotation SummarizationSetBy = Automatic

	partition TipoInstitucion = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(url_db),[Delimiter=",", Columns=28, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Encabezados promovidos",{"STATUS"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Filas ordenadas" = Table.Sort(#"Duplicados quitados",{{"STATUS", Order.Ascending}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Filas ordenadas", "Índice", 1, 1, Int64.Type),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Índice agregado",{"Índice", "STATUS"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Índice", "Codigo Tipo Institucion"}, {"STATUS", "Tipo Institucion"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

